version: '2'

services:
  frontend:
    image: yarmolovichalex1/frontend:latest
    build:
      context: ./src/Frontend
      dockerfile: Dockerfile
    depends_on:
      - webapi

  webapi:
    image: yarmolovichalex1/webapi:latest
    build:
      context: ./src/WebApi
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    restart: always

  writemodel:
    image: yarmolovichalex1/writemodel:latest
    build:
      context: ./src/WriteModel
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - eventstore
    restart: always

  readmodel:
    image: yarmolovichalex1/readmodel:latest
    build:
      context: ./src/ReadModel
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    restart: always

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management

  eventstore:
    container_name: eventstore
    image: eventstore/eventstore:latest

  mongo:
    container_name: mongo
    image: mongo:latest

  redis:
    container_name: redis
    image: redis:latest