version: '2'

services:
  frontend:
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  webapi:
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  writemodel:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  readmodel:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  eventstore:
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - eventstore:/var/lib/eventstore

  mongo:
    ports:
      - "27017:27017"

  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis:/data

volumes:
  redis:
  rabbitmq:
  eventstore: