version: '2'

services:
  frontend:
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  webapi:
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  writemodel:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  readmodel:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  eventstore:
    ports:
      - "1113:1113"
      - "2113:2113"

  mongo:
    ports:
      - "27017:27017"

  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes