version: '2'

services:
  frontend:
    image: frontend
    build:
      context: ./src/Frontend
      dockerfile: Dockerfile
    ports:
     - "5000:5000"

  webapi:
    image: webapi
    build:
      context: ./src/WebApi
      dockerfile: Dockerfile

  writemodel:
    image: writemodel
    build:
      context: ./src/WriteModel
      dockerfile: Dockerfile

  readmodel:
    image: readmodel
    build:
      context: ./src/ReadModel
      dockerfile: Dockerfile
