version: '3'
services:
  rabbit:
    container_name: rabbit
    image: "rabbitmq:3-management"
    ports:
     - "8080:15672"
  eventstore:
    container_name: eventstore
    image: "eventstore/eventstore"
    ports:
      - "2113:2113"
      - "1113:1113"
  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - "27017:27017"
  web:
    container_name: web
    build: ./WebApi
    ports:
     - "8000:80"
    depends_on:
      - rabbit
    restart: always
  write_model:
    container_name: write_model
    build: ./WriteModel
    depends_on:
      - rabbit
      - eventstore
    restart: always
  read_model:
    container_name: read_model
    build: ./ReadModel
    depends_on:
      - rabbit
      - mongo
    restart: always
