version: '3'
services:
  rabbit:
    container_name: rabbit
    image: "rabbitmq:3-management"
    ports:
     - "15672:15672"
     - "5672:5672"
  eventstore:
    container_name: eventstore
    image: "eventstore/eventstore"
    ports:
      - "2113:2113"
      - "1113:1113"
  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - "27017:27017"
  frontend:
    container_name: frontend
    build: ./Frontend
    ports:
     - "5000:80"
    depends_on:
      - web-api
    restart: always
  web-api:
    container_name: web-api
    build: ./WebApi
    ports:
     - "5001:5001"
    depends_on:
      - rabbit
    restart: always
  write_model:
    container_name: write-model
    build: ./WriteModel
    depends_on:
      - rabbit
      - eventstore
    restart: always
  read_model:
    container_name: read-model
    build: ./ReadModel
    depends_on:
      - rabbit
      - mongo
    restart: always
